### ISSUE TITLE
Cross-compilation fails with "target may not be installed", missing std crate for #[no_std] project

### ISSUE THREAD

**Issue by noonien** [oxalica/rust-overlay#12]
I've got the following:

<details>
  <summary>flake.nix</summary>

  ```nix
  {
    description = "A very basic flake";
  
    inputs = {
      nixpkgs.url = "nixpkgs/nixos-20.09";
  
      rust-overlay = {
        url = "github:oxalica/rust-overlay";
        inputs.nixpkgs.follows = "nixpkgs";
      };
  
      naersk = {
        url = "github:nmattia/naersk";
        inputs.nixpkgs.follows = "nixpkgs";
      };
    };
  
    outputs = { self, nixpkgs, rust-overlay, naersk }:
      let
        systems = [
          "aarch64-linux"
          "x86_64-linux"
        ];
  
        eachSystem = systems: f: builtins.foldl' (attrs: system: attrs // { ${system} = f system; }) { } systems;
      in
      {
        packages = eachSystem systems
          (system:
            let
              pkgs = import nixpkgs { inherit system; overlays = [ rust-overlay.overlay ]; };
              toolchain = pkgs.rust-bin.fromRustupToolchainFile ./rust-toolchain;
            in
            {
              fw = (naersk.lib.${system}.override {
                cargo = toolchain;
                rustc = toolchain;
              }).buildPackage {
                src = ./sbs-fw;
              };
            }
          );
      };
  }
  ```
</details>

<details>
  <summary>rust-toolchain</summary>

  ```toml
  [toolchain]
  channel = "nightly-2021-01-27"
  components = [ "clippy-preview", "miri-preview", "rls-preview", "rust-analysis", "rust-analyzer-preview", "rustfmt", "llvm-tools-preview", "rust-src", "rust-std" ]
  targets = [ "thumbv7m-none-eabi", "x86_64-pc-windows-gnu", "x86_64-unknown-linux-gnu" ]
  ```
</details>

`cargo build` in the sbs-fw directory works just fine, however, when doing a `nix build .#fw` the following error occurs:
```
sbs-fw-deps>    Compiling stm32f1xx-hal v0.6.1
sbs-fw-deps> error: could not compile `sbs-fw`
sbs-fw-deps> To learn more, run the command again with --verbose.
sbs-fw-deps> warning: build failed, waiting for other jobs to finish...
sbs-fw-deps> error: build failed
sbs-fw-deps> error[E0463]: can't find crate for `std`
sbs-fw-deps>   |
sbs-fw-deps>   = note: the `thumbv7m-none-eabi` target may not be installed
sbs-fw-deps> error: aborting due to previous error
sbs-fw-deps> For more information about this error, try `rustc --explain E0463`.
sbs-fw-deps> [naersk] cargo returned with exit code 101, exiting
error: --- Error --- nix-daemon
builder for '/nix/store/azanh3lgylx1gpcdbbdsqzkjy83hp0kp-sbs-fw-deps-0.1.0.drv' failed with exit code 101; last 10 log lines:
    |
    = note: the `thumbv7m-none-eabi` target may not be installed
  
  
  error: aborting due to previous error
  
  
  For more information about this error, try `rustc --explain E0463`.
  
  [naersk] cargo returned with exit code 101, exiting
```

I tried adding "rust-std-thumbv7m-none-eabi" to "components" in rust-toolchain, however, rust-overlay complains that's not a valid component. `rustup` does install it for each target though.

Edit: forgot to mention, this ia a #[no_std] embedded project.
Edit:
The user-installed rustup reports the following components:
```
$ rustup component list | rg installed
cargo-x86_64-unknown-linux-gnu (installed)
clippy-x86_64-unknown-linux-gnu (installed)
llvm-tools-preview-x86_64-unknown-linux-gnu (installed)
miri-x86_64-unknown-linux-gnu (installed)
rls-x86_64-unknown-linux-gnu (installed)
rust-analysis-x86_64-unknown-linux-gnu (installed)
rust-analyzer-preview-x86_64-unknown-linux-gnu (installed)
rust-docs-x86_64-unknown-linux-gnu (installed)
rust-src (installed)
rust-std-thumbv7m-none-eabi (installed)
rust-std-x86_64-pc-windows-gnu (installed)
rust-std-x86_64-unknown-linux-gnu (installed)
rustc-x86_64-unknown-linux-gnu (installed)
rustfmt-x86_64-unknown-linux-gnu (installed)
```

**Comment by oxalica** [comment]
What are your build system and build command?
I'm on x86_64 and `nix build .#fw` simply builds x86_64 binary successfully. There is no cross compilation since no `crossSystem` specified for nixpkgs and no `--target` argument for cargo.

Not quite familiar to nmattia/naersk. Does it do some magic?

**Comment by noonien** [comment]
The project itself is setup for compiling to the right architecture, like so:

<details>
<summary>.cargo/config</summary>

```toml
[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "gdb -q -x openocd.gdb"

rustflags = [
  # LLD (shipped with the Rust toolchain) is used as the default linker
  "-C", "link-arg=-Tlink.x",
]

[build]
target = "thumbv7m-none-eabi"    # Cortex-M3
```
</details>

I'll try to upload a a more complete code to reproduce soon.
